// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA53wNEyNRp8JdypxNnBwq8B9VkUVvtViQ',
    appId: '1:17460889026:web:df18f0623e5fd690dd825b',
    messagingSenderId: '17460889026',
    projectId: 'study-5573d',
    authDomain: 'study-5573d.firebaseapp.com',
    storageBucket: 'study-5573d.appspot.com',
    measurementId: 'G-J87MWYL82V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc7YTiSGl9r_b16uPajuOr5LQo_7ZRA-k',
    appId: '1:17460889026:android:f82b9e55f777dda6dd825b',
    messagingSenderId: '17460889026',
    projectId: 'study-5573d',
    storageBucket: 'study-5573d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZnwE360sUlNjTaGmwpBFYKzsNsGgRP5E',
    appId: '1:17460889026:ios:ce8b12f1db19337ddd825b',
    messagingSenderId: '17460889026',
    projectId: 'study-5573d',
    storageBucket: 'study-5573d.appspot.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZnwE360sUlNjTaGmwpBFYKzsNsGgRP5E',
    appId: '1:17460889026:ios:06726bdd6dd63458dd825b',
    messagingSenderId: '17460889026',
    projectId: 'study-5573d',
    storageBucket: 'study-5573d.appspot.com',
    iosBundleId: 'com.example.hackathon.RunnerTests',
  );
}
